### ISSUE TITLE
[Doubt] What will happen to this amazing mod?

### ISSUE THREAD

**Issue by gatoborrachon** [trentv4/GlennsGases#6]
Hello, while i was looking on the issues from the 1.7 version, i found a link to this repo, what will happen with the mod? it is the best alternative to Pollution of the Realms (i want gases, but Pollution of the Realms has not the amazing features from Gases Framework)

**Comment by trentv4** [comment]
The mod has been discontinued. If you want to fork it and update, feel free! I believe I left the codebase in excellent shape.

**Comment by gatoborrachon** [comment]
oh, ok, its a shame to hear that, i don't have the enough knowledge nor the time, but ok, many thanks for answer
